global: &global
  adapter: postgresql
  min_messages: warning
  encoding: unicode
  host: localhost

development:
  database: glosario_development
  <<: *global

test: &test
  database: glosario_test
  <<: *global
