# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82d7e29eb76a4d668922b90e68f1ec9f43ebb79a8980b94adeba88e0c2938ef1a92eb95c7089c9a0981297eeee1b3c8cdbf11dbb28865b9c000976d0349b3316
  secret_token: dcc2e896e638af9a395011dd4088ecf56d8da3a8a603003e7a4a9a5c841efc2c8a3c222345316afd24d4b46b4229aa311ca6f91fe50e502fb5bdb5e962fe14c2

test:
  secret_key_base: eadbe71899dcca2b6531c96d54e8be8458057e21bbc7d51e2d44f47ed4c2bdc3baffc5a3c580fea9c0b109e7f6ac28a64c4b772b963deb22f33270919e52172f
  secret_token: f4bd2b1dd0b5e1a34d2f51bf680e28e051744d18fa8674bd000bab9824f1eead78b576e7bff65009adca9120550efbc14ab63128315e1db463e2ba6a1e230b5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
